# Generated by Django 4.1.2 on 2023-03-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bears', '0002_sighting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='temperature',
            field=models.TextField(),
        ),
    ]
